version: '3'
services:
  build-template:
    build:
      context: .
      dockerfile: Dockerfile.buildenv
    image: build-template
  controller-050:
    build:
      context: .
      dockerfile: Dockerfile.controller
      args:
        - TAG=v0.5.0
    tmpfs: /tmp
    volumes:
      - ccache:/mnt/ccache
      - builds:/mnt/builds

volumes:
  ccache:
  builds:
