version: '3.7'

x-controller:
  &controller-template
  tmpfs: /tmp
  environment:
    - CCACHE_DIR="/mnt/ccache"
  secrets:
    - github_apikey
  volumes:
    - ccache:/mnt/ccache
    - ./tmp_config:/mnt/config
    - ./tmp_builds:/mnt/builds
  # Remove me when ubuntu 14.04 is less shitty
  network_mode: "host"
  dns: 8.8.8.8

x-build:
  &build-defaults
  context: .
  dockerfile: Dockerfile

services:
  build-template:
    build:
      context: .
      dockerfile: Dockerfile.buildenv
    image: build-template

  controller-050:
    << : *controller-template
    build:
      << : *build-defaults
      args:
        - TAG=v0.5.0

  controller-053:
    << : *controller-template
    build:
      << : *build-defaults
      args:
        - TAG=v0.5.3

secrets:
  github_apikey:
    file: ./apikey

volumes:
  ccache:
